//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ApiKeys = new HashSet<ApiKey>();
            this.Groups = new HashSet<Group>();
            this.Messages = new HashSet<Message>();
            this.Payments = new HashSet<Payment>();
            this.Templates = new HashSet<Template>();
            this.Tokens = new HashSet<Token>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public double Balance { get; set; }
        public int Role { get; set; }
        public string RegTime { get; set; }
        public Nullable<int> MaxContacts { get; set; }
        public Nullable<int> MaxApiKeys { get; set; }
        public Nullable<int> MaxTemplates { get; set; }
    
        public virtual ICollection<ApiKey> ApiKeys { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
        public virtual ICollection<Token> Tokens { get; set; }
    }
}
