//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PlanId { get; set; }
        public string Status { get; set; }
        public double Amount { get; set; }
        public Nullable<double> Fee { get; set; }
        public string Method { get; set; }
        public string RefNo { get; set; }
        public string TxnNo { get; set; }
        public string CreatedAt { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual User User { get; set; }
    }
}
